---

- name: make sure that all web writable folders exist
  file: path="{{ item.name }}" state=directory recurse=yes
  with_items: "{{ web_writable_folders }}"

- name: Set deploy_user ACL privileges on directories
  acl: name={{ item.name }} entity={{ deploy_user }} etype=user permissions=rwX state=present recursive={{ item.recursive }}
  with_items: "{{ web_writable_folders }}"

- name: Set deploy_user default ACL privileges on directories
  acl: name={{ item.name }} entity={{ deploy_user }} etype=user permissions=rwX default=yes state=present recursive={{ item.recursive }}
  with_items: "{{ web_writable_folders }}"

- name: Set web_user ACL privileges on directories
  acl: name={{ item.name }} entity={{ nginx_user }} etype=user permissions=rwX state=present recursive={{ item.recursive }}
  with_items: "{{ web_writable_folders }}"

- name: Set web_user default ACL privileges on directories
  acl: name={{ item.name }} entity={{ nginx_user }} etype=user permissions=rwX default=yes state=present recursive={{ item.recursive }}
  with_items: "{{ web_writable_folders }}"

- name: Run database migrations
  command: "bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --env=prod chdir={{ deploy_helper.new_release_path }}"

- name: Warmup cache
  command: bin/console cache:warmup
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  environment: "{{ project_environment }}"
